export enum ErrorCode {
    // Validation errors (400)
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    INVALID_INPUT = 'INVALID_INPUT',

    // Authentication errors (401)
    AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    TOKEN_INVALID = 'TOKEN_INVALID',

    // Authorization errors (403)
    AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
    INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

    // Not found errors (404)
    NOT_FOUND = 'NOT_FOUND',
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

    // Conflict errors (409)
    CONFLICT = 'CONFLICT',
    DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',

    // Database errors (500)
    DATABASE_ERROR = 'DATABASE_ERROR',
    DATABASE_CONNECTION_ERROR = 'DATABASE_CONNECTION_ERROR',
    DATABASE_QUERY_ERROR = 'DATABASE_QUERY_ERROR',

    // External service errors (502-504)
    EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
    GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT',

    // Internal errors (500)
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
