import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import { GraphQLSchemaBuilderModule, GraphQLSchemaFactory } from '@nestjs/graphql';
import { printSchema } from 'graphql';
import { AppModule } from '../src/app.module';
import { DateScalar } from '../src/common/scalars/date.scalar';
import * as fs from 'fs';
import * as path from 'path';

// Skip DB connection during schema generation
process.env.SKIP_DB_CONNECTION = 'true';

async function generateSchema() {
    console.log('Generating schema...');

    // We need to create the full application context to ensure all modules and resolvers are loaded
    let fullApp;
    try {
        fullApp = await NestFactory.create(AppModule, { logger: false });
        await fullApp.init();

        // The schema is automatically generated by GraphQLModule on init because of autoSchemaFile
        // But if we want to explicitly write it or manipulate it:

        // Let's verify it exists
        const schemaPath = path.join(process.cwd(), 'schema.gql');
        if (fs.existsSync(schemaPath)) {
            console.log(`✅ Schema generated at ${schemaPath}`);
        } else {
            console.error('❌ Schema generation failed');
            process.exit(1);
        }
    } catch (error) {
        fs.writeFileSync('error.log', JSON.stringify(error, Object.getOwnPropertyNames(error), 2));
        console.error('❌ Schema generation failed. Check error.log for details.');
        process.exit(1);
    }

    if (fullApp) {
        await fullApp.close();
    }
}

generateSchema();
